import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Search from "@/components/Search/Search";
import { wrapper } from "@/store";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Search />
        {children}
      </body>
    </html>
  );
}

export default wrapper.withRedux(RootLayout);
